#!bin/sh
if [[ -z "$DOTFILES_DIR" ]]; then
	echo "it's not a valid execution..."
	exit
fi

DIR="$DOTFILES_DIR/$(dirname $BASH_SOURCE)"
MATCHES="*.sh"

for FILE in $(find "$DIR" -type f -iname "$MATCHES"); do
	source $FILE
done

unset DIR MATCHES FILE
