#!bin/sh
if [[ -z "$BASH_SOURCE" ]]; then
	BASH_SOURCE=$0
fi

DIR=$DOTFILES_DIR/$(dirname $BASH_SOURCE)

load_sources $DIR/helpers

# call an sh function using string name
# eval "print_info 'hello setup.sh'"

load_source $DIR/prepare.sh
load_source $DIR/xcode_cli.sh
load_source $DIR/git.sh
load_source $DIR/python.sh
load_source $DIR/node.sh
load_source $DIR/brew.sh
load_source $DIR/install.sh

unset DIR
