#!bin/sh
if [[ -z "$BASH_SOURCE" ]]; then
  BASH_SOURCE=$0
fi

DIR=$DOTFILES_DIR/$(dirname $BASH_SOURCE)

# call an sh function using string name
# eval "print_info 'hello setup.sh'"

print_set_vars

load_source $DIR/prepare.sh
load_source $DIR/xcode_cli.sh
# load_source $DIR/oh_my_zsh.sh
# load_source $DIR/git.sh
# load_source $DIR/python.sh
load_source $DIR/node_nvm.sh
load_source $DIR/brew.sh
load_source $DIR/install.sh
load_source $DIR/macos.sh
load_source $DIR/system.sh
load_source $DIR/node.sh

print_unset_vars

unset DIR

print_done "full setup"
